### ISSUE TITLE
Create Bower Package

### ISSUE THREAD

**Issue by craigmdennis** [ten1seven/trackFocus#2]
It would be great to see a bower.json file in the repo

**Comment by ten1seven** [comment]
Just added it!

**Comment by craigmdennis** [comment]
You also need to register it with Bower to allow for `bower install trackFocus` http://bower.io/docs/creating-packages/#register

**Comment by ten1seven** [comment]
Looks like it's showing up now.

**Comment by craigmdennis** [comment]
Nice :)

**Comment by craigmdennis** [comment]
The `name` in the `bower.json` file is set to `trackFocus` but it's seems to be registered as `track-focus` on Bower. Not sure if they should be the same.

**Comment by ten1seven** [comment]
Updated. Didn't seem to effect searching for the package but now it's consistent.

**Comment by ten1seven** [comment]
Hey @craigmdennis, check out my new project [What Input?](https://github.com/ten1seven/what-input). It improves on track-focus by being more generic and exposing an API for scripting. I feel that it's different enough that it needed to be its own repo instead of a revision to track-focus.
